name: build-ios

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build unsigned IPA
        run: flutter build ipa --no-codesign --export-options-plist ios/Flutter/exportOptions.plist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: solara-ios-build
          path: |
            build/ios/ipa/*.ipa
            build/ios/archive/*.xcarchive
