name: build-ios

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build Solara (iOS)
        run: |
          # Fix line continuation syntax
          xcodebuild \
            -project Solara.xcodeproj \
            -scheme Solara \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Package IPA
        run: |
          mkdir Payload
          cp -r build/Build/Products/Release-iphoneos/Solara.app Payload/
          zip -r Solara.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Solara-IPA
          path: Solara.ipa
